# example netlify.toml
[build]
  command = "find / -name is-unicode-supported && cypress install && astro build"
  functions = "netlify/functions"
  publish = "dist"

# [[plugins]] 
#   package = "netlify-plugin-cypress"

#   [plugins.inputs.postBuild]
#     enable = true
  
#   [plugin.inputs]
#     enable = false
